name: Deploy Kafka and Zookeeper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Start Kafka and Zookeeper with Docker Compose
      - name: Start Kafka and Zookeeper
        run: |
          docker-compose -f docker-compose.yml up -d

      # Step 4: Verify Kafka and Zookeeper (Optional)
      - name: Verify Kafka and Zookeeper
        run: |
          docker ps

      # Step 5: Run ./con.sh Script
      - name: Run ./con.sh Script
        run: |
          chmod +x ./con.sh
          ./con.sh
